# Generated by Django 4.0 on 2021-12-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('page_num', models.IntegerField(blank=True, null=True)),
                ('land', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
