# Generated by Django 4.0 on 2021-12-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_buss_latitude_buss_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
