# Generated by Django 4.0 on 2021-12-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_buss_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
