# Generated by Django 4.0.1 on 2022-01-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_buss_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss',
            name='facebook',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='buss',
            name='organization_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
