# Generated by Django 4.0.1 on 2022-01-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_buss_facebook_buss_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss',
            name='availablity_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buss',
            name='donation_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
